In [1]:
import numpy as np

from cfair.backends import NumpyBackend
from cfair.metrics.kernel.hgr import CategoricalHGR

In [ ]:
# DEBUG

def one_hot_encode(x):
        unique_vals = np.unique(x)
        return np.array([[1 if val == xi else 0 for val in unique_vals] for xi in x])

# DEBUG

In [2]:
backend = NumpyBackend()

one_hot_hgr = CategoricalHGR(
    backend=backend,
    method='trust-constr',
    maxiter=1000,
    eps=1e-9,
    tol=1e-9,
    use_lstsq=True,
    delta_independent=None
)

# First Example - corr = 0

In [16]:
# Example categorical data
a = np.array(['cat', 'dog', 'cat', 'bird'])
b = np.array(['red', 'red', 'blue', 'green'])

In [17]:

ohe_a = one_hot_encode(a)
ohe_b = one_hot_encode(b)

In [18]:
print(ohe_a)

[[0 1 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]]


In [19]:
print(ohe_b)

[[0 0 1]
 [0 0 1]
 [1 0 0]
 [0 1 0]]


In [20]:
result = one_hot_hgr._compute(a, b)
print(result)

None


In [21]:
corr, alpha, beta = one_hot_hgr._indicator(ohe_a, ohe_b, None, None)
print(corr, alpha, beta)

0.0 [0.33334152 0.33334152 0.33334152] [0.33333333 0.33333333 0.33333333]


# Second Example - corr = 0

In [23]:
c = np.array(['cat', 'dog', 'cat', 'bird'])
d = np.array(['cat', 'dog', 'cat', 'bird'])

In [27]:
ohe_c = one_hot_encode(c)
ohe_d = one_hot_encode(d)

In [28]:
print(ohe_c)

[[0 1 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]]


In [29]:
print(ohe_d)

[[0 1 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]]


In [30]:
result = one_hot_hgr._compute(c, d)
print(result)

None


In [31]:
corr, alpha, beta = one_hot_hgr._indicator(ohe_c, ohe_d, None, None)
print(corr, alpha, beta)

0.0 [0.33334152 0.33334152 0.33334152] [0.33333333 0.33333333 0.33333333]
