# Toy Class

In [ ]:
toy_one_hot_hgr = CategoricalHGR(
    backend=backend,
    method='trust-constr',
    maxiter=1000,
    eps=1e-9,
    tol=1e-9,
    use_lstsq=True,
    delta_independent=None
)

## First Example - corr = 0

In [ ]:
# Example categorical data
a = np.array(['cat', 'dog', 'cat', 'bird'])
b = np.array(['red', 'red', 'blue', 'green'])

In [ ]:

ohe_a = one_hot_encode(a)
ohe_b = one_hot_encode(b)

In [ ]:
print(ohe_a)

[[0 0 0 1]
 [1 0 1 0]
 [0 1 0 0]]


In [ ]:
print(ohe_b)

[[0 0 1 0]
 [0 0 0 1]
 [1 1 0 0]]


In [ ]:
result = toy_one_hot_hgr._compute(a, b)
print(result)

None


In [ ]:
corr, alpha, beta = toy_one_hot_hgr._indicator(ohe_a, ohe_b, None, None)
print(corr, alpha, beta)

0.9449111800932964 [0.19385645 0.54457232 0.19385645 0.30321213] [0.22038587 0.22038587 0.24541706 0.3138112 ]


## Second Example - corr = 0

In [ ]:
c = np.array(['cat', 'dog', 'cat', 'bird'])
d = np.array(['cat', 'dog', 'cat', 'bird'])

In [ ]:
ohe_c = one_hot_encode(c)
ohe_d = one_hot_encode(d)

In [ ]:
print(ohe_c)

[[0 0 0 1]
 [1 0 1 0]
 [0 1 0 0]]


In [ ]:
print(ohe_d)

[[0 0 0 1]
 [1 0 1 0]
 [0 1 0 0]]


In [ ]:
result = toy_one_hot_hgr._compute(c, d)
print(result)

None


In [ ]:
corr, alpha, beta = toy_one_hot_hgr._indicator(ohe_c, ohe_d, None, None)
print(corr, alpha, beta)

0.999999998875 [0.26516504 0.26516504 0.26516504 0.26516504] [0.25 0.25 0.25 0.25]


## Joke Experiment

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

result_p = polynomial_kernel._compute(a, b)

In [ ]:
print(result_p.value)

0.9999999989999997


In [ ]:
print(result_p.alpha)

[-0.98971955 -0.01028045]


In [ ]:
print(result_p.beta)

[ 9.90848562e-01 -9.15143279e-03 -5.25302806e-09]


## 50000, all random

In [ ]:
num1 = []
num2 = []

for i in range(50000):
    num1.append(rn.randint(0,9))
    num2.append(rn.randint(0,9))

In [ ]:
result_50000_pol = polynomial_kernel._compute(num1, num2)

In [ ]:
print(result_50000_pol.value)

0.002260964800911911


In [ ]:
print(result_50000_pol.alpha)

[ 0.95591086 -0.04408914]


In [ ]:
print(result_50000_pol.beta)

[ 0.79060664 -0.14080855  0.0685848 ]


## Experiment 1 (numbers)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 2, 2, 1])

# Compute the HGR indicator
result1 = my_kernel_one_hot._compute(a, b)

In [ ]:
print(result1.value)

0.9999999990000001


In [ ]:
print(result1.alpha)

[0.20000184 0.20000837 0.20000051 0.20000051 0.19998878]


In [ ]:
print(result1.beta)

[0.24998613 0.25000079 0.25001062 0.25000246]


## Experiment 2 (categorical)

In [ ]:
a2 = np.array(['cat', 'dog', 'cat', 'dog'])
b2 = np.array(['sus', 'sis', 'sus', 'ses'])

result2 = my_kernel_one_hot._compute(a2, b2)

In [ ]:
print(result2.value)

0.9999999989999999


In [ ]:
print(result2.a)

['cat' 'dog' 'cat' 'dog']


In [ ]:
print(result2.b)

['sus' 'sis' 'sus' 'ses']


In [ ]:
print(result2.alpha)

[0.49998419 0.50001581]


In [ ]:
print(result2.beta)

[0.33334036 0.33334036 0.33331928]


## DEBUG CONCATENATION

In [ ]:
f = [ [1, 0],[0, 1],[1, 0],[1, 0] ]

f = np.stack(f, axis=1)
f = f - np.mean(f, axis=0)

print(f)

# g = np.stack(g, axis=1)
# g = g - np.mean(g, axis=0)

# print(g)

[[ 0.5 -0.5  0.5  0.5]
 [-0.5  0.5 -0.5 -0.5]]
