# Toy Class

In [ ]:
toy_one_hot_hgr = CategoricalHGR(
    backend=backend,
    method='trust-constr',
    maxiter=1000,
    eps=1e-9,
    tol=1e-9,
    use_lstsq=True,
    delta_independent=None
)

## First Example - corr = 0

In [ ]:
# Example categorical data
a = np.array(['cat', 'dog', 'cat', 'bird'])
b = np.array(['red', 'red', 'blue', 'green'])

In [ ]:

ohe_a = one_hot_encode(a)
ohe_b = one_hot_encode(b)

In [ ]:
print(ohe_a)

[[0 0 0 1]
 [1 0 1 0]
 [0 1 0 0]]


In [ ]:
print(ohe_b)

[[0 0 1 0]
 [0 0 0 1]
 [1 1 0 0]]


In [ ]:
result = toy_one_hot_hgr._compute(a, b)
print(result)

None


In [ ]:
corr, alpha, beta = toy_one_hot_hgr._indicator(ohe_a, ohe_b, None, None)
print(corr, alpha, beta)

0.9449111800932964 [0.19385645 0.54457232 0.19385645 0.30321213] [0.22038587 0.22038587 0.24541706 0.3138112 ]


## Second Example - corr = 0

In [ ]:
c = np.array(['cat', 'dog', 'cat', 'bird'])
d = np.array(['cat', 'dog', 'cat', 'bird'])

In [ ]:
ohe_c = one_hot_encode(c)
ohe_d = one_hot_encode(d)

In [ ]:
print(ohe_c)

[[0 0 0 1]
 [1 0 1 0]
 [0 1 0 0]]


In [ ]:
print(ohe_d)

[[0 0 0 1]
 [1 0 1 0]
 [0 1 0 0]]


In [ ]:
result = toy_one_hot_hgr._compute(c, d)
print(result)

None


In [ ]:
corr, alpha, beta = toy_one_hot_hgr._indicator(ohe_c, ohe_d, None, None)
print(corr, alpha, beta)

0.999999998875 [0.26516504 0.26516504 0.26516504 0.26516504] [0.25 0.25 0.25 0.25]


## Joke Experiment

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

result_p = polynomial_kernel._compute(a, b)

In [ ]:
print(result_p.value)

0.9999999989999997


In [ ]:
print(result_p.alpha)

[-0.98971955 -0.01028045]


In [ ]:
print(result_p.beta)

[ 9.90848562e-01 -9.15143279e-03 -5.25302806e-09]


## 50000, all random

In [ ]:
num1 = []
num2 = []

for i in range(50000):
    num1.append(rn.randint(0,9))
    num2.append(rn.randint(0,9))

In [ ]:
result_50000_pol = polynomial_kernel._compute(num1, num2)

In [ ]:
print(result_50000_pol.value)

0.002260964800911911


In [ ]:
print(result_50000_pol.alpha)

[ 0.95591086 -0.04408914]


In [ ]:
print(result_50000_pol.beta)

[ 0.79060664 -0.14080855  0.0685848 ]


## Experiment 1 (numbers)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 2, 2, 1])

# Compute the HGR indicator
result1 = my_kernel_one_hot._compute(a, b)

In [ ]:
print(result1.value)

0.9999999990000001


In [ ]:
print(result1.alpha)

[0.20000184 0.20000837 0.20000051 0.20000051 0.19998878]


In [ ]:
print(result1.beta)

[0.24998613 0.25000079 0.25001062 0.25000246]


## Experiment 2 (categorical)

In [ ]:
a2 = np.array(['cat', 'dog', 'cat', 'dog'])
b2 = np.array(['sus', 'sis', 'sus', 'ses'])

result2 = my_kernel_one_hot._compute(a2, b2)

In [ ]:
print(result2.value)

0.9999999989999999


In [ ]:
print(result2.a)

['cat' 'dog' 'cat' 'dog']


In [ ]:
print(result2.b)

['sus' 'sis' 'sus' 'ses']


In [ ]:
print(result2.alpha)

[0.49998419 0.50001581]


In [ ]:
print(result2.beta)

[0.33334036 0.33334036 0.33331928]


## DEBUG CONCATENATION

In [ ]:
f = [ [1, 0],[0, 1],[1, 0],[1, 0] ]

f = np.stack(f, axis=1)
f = f - np.mean(f, axis=0)

print(f)

# g = np.stack(g, axis=1)
# g = g - np.mean(g, axis=0)

# print(g)

[[ 0.5 -0.5  0.5  0.5]
 [-0.5  0.5 -0.5 -0.5]]


# Warriors/Animals experiments (NO PLOTS)

## 1. All Random

In [ ]:
ani = []
war = []

for i in range(50000):
    ani.append(sample(animals))
    war.append(sample(warriors))

In [ ]:
print(ani)

['dog', 'dog', 'horse', 'dog', 'dog', 'cat', 'cat', 'horse', 'cat', 'horse', 'horse', 'monke', 'dog', 'cat', 'monke', 'dog', 'horse', 'horse', 'monke', 'cat', 'cat', 'dog', 'monke', 'cat', 'cat', 'horse', 'cat', 'cat', 'cat', 'horse', 'monke', 'cat', 'horse', 'monke', 'cat', 'monke', 'horse', 'monke', 'cat', 'monke', 'monke', 'dog', 'dog', 'horse', 'monke', 'monke', 'horse', 'monke', 'horse', 'monke', 'monke', 'dog', 'cat', 'monke', 'horse', 'cat', 'horse', 'dog', 'cat', 'monke', 'horse', 'dog', 'dog', 'horse', 'dog', 'cat', 'dog', 'cat', 'horse', 'monke', 'monke', 'horse', 'horse', 'dog', 'horse', 'horse', 'horse', 'monke', 'horse', 'cat', 'horse', 'dog', 'cat', 'dog', 'dog', 'dog', 'monke', 'horse', 'horse', 'monke', 'dog', 'dog', 'cat', 'horse', 'monke', 'dog', 'horse', 'monke', 'horse', 'monke', 'dog', 'horse', 'monke', 'dog', 'horse', 'monke', 'monke', 'horse', 'horse', 'dog', 'cat', 'monke', 'monke', 'dog', 'cat', 'horse', 'horse', 'monke', 'dog', 'cat', 'monke', 'cat', 'dog', 'h

In [ ]:
print(np.unique(ani))

['cat' 'dog' 'horse' 'monke']


In [ ]:
print(war)

['Salamander', 'Dark Angel', 'Blood Angel', 'Imperial Fist', 'Space Wolf', 'White Scar', 'Space Wolf', 'Ultramarine', 'Raven Guard', 'Raven Guard', 'Imperial Fist', 'Raven Guard', 'Salamander', 'White Scar', 'Ultramarine', 'Imperial Fist', 'Imperial Fist', 'Raven Guard', 'Ultramarine', 'Iron Hand', 'Space Wolf', 'Ultramarine', 'White Scar', 'Iron Hand', 'Blood Angel', 'Space Wolf', 'White Scar', 'Blood Angel', 'Dark Angel', 'Blood Angel', 'Ultramarine', 'Raven Guard', 'White Scar', 'Salamander', 'Space Wolf', 'Raven Guard', 'Ultramarine', 'Ultramarine', 'Iron Hand', 'Dark Angel', 'Imperial Fist', 'Space Wolf', 'Imperial Fist', 'Ultramarine', 'Iron Hand', 'White Scar', 'Imperial Fist', 'Blood Angel', 'Salamander', 'Raven Guard', 'Ultramarine', 'Raven Guard', 'Dark Angel', 'Iron Hand', 'White Scar', 'Space Wolf', 'Salamander', 'Ultramarine', 'White Scar', 'Iron Hand', 'Space Wolf', 'White Scar', 'Imperial Fist', 'Imperial Fist', 'Blood Angel', 'Raven Guard', 'Imperial Fist', 'Iron Hand',

In [ ]:
print(np.unique(war))

['Blood Angel' 'Dark Angel' 'Imperial Fist' 'Iron Hand' 'Raven Guard'
 'Salamander' 'Space Wolf' 'Ultramarine' 'White Scar']


In [ ]:
result_ar = my_kernel_one_hot._result(war, ani, kernel_a=True, kernel_b=True, a0=np.ones(9), b0=np.ones(4))#_compute(war, ani)

In [ ]:
print(result_ar.value)

0.013640270441203405


In [ ]:
print(result_ar.alpha)

[0.10951461 0.11114429 0.11108475 0.10974085 0.1119761  0.10937825
 0.11072373 0.11194177 0.11449566]


In [ ]:
print(result_ar.beta)

[0.25146512 0.24500797 0.00584132 0.49768559]


### Confusion Matrix extravaganza All Random

In [ ]:
legionAllRand = pd.DataFrame({'warrior': war, 'steed': ani})

In [ ]:
legionAllRand

warrior  steed
0         Salamander    dog
1         Dark Angel    dog
2        Blood Angel  horse
3      Imperial Fist    dog
4         Space Wolf    dog
...              ...    ...
49995     Dark Angel    dog
49996      Iron Hand    dog
49997    Ultramarine  horse
49998    Ultramarine  horse
49999    Ultramarine    dog

[50000 rows x 2 columns]

In [ ]:
confusion_matrix = pd.crosstab(legionAllRand['warrior'], legionAllRand['steed'])
print(confusion_matrix)

steed           cat   dog  horse  monke
warrior                                
Blood Angel    1351  1398   1447   1387
Dark Angel     1318  1388   1340   1339
Imperial Fist  1407  1392   1370   1366
Iron Hand      1404  1412   1363   1313
Raven Guard    1407  1417   1349   1377
Salamander     1343  1387   1428   1364
Space Wolf     1332  1449   1422   1406
Ultramarine    1414  1399   1414   1440
White Scar     1429  1441   1334   1453


In [ ]:
cramers_v(confusion_matrix.values)

0.0010153983803798156

## 2. Autocorrelation

In [ ]:
result_auto = my_kernel_one_hot._result(war, war, kernel_a=True, kernel_b=True, a0=np.ones(9), b0=np.ones(9))#_compute(war, war)

In [ ]:
print(result_auto.value)

0.9999999989998559


In [ ]:
print(result_auto.alpha)

[ 0.21378415  0.13514972  0.03297666  0.14790576  0.17822336 -0.07013673
  0.18748976 -0.00589562  0.02843825]


In [ ]:
print(result_auto.beta)

[ 0.21350667  0.13645517  0.03633887  0.14895442  0.17866173 -0.06469883
  0.18774159 -0.00175091  0.03189182]


It is VERY HIGH -> as i expected, VERY GOODDE!!

### Confusion Matrix extravaganza Autoc

In [ ]:
legionAuto = pd.DataFrame({'warrior1': war, 'warrior2': war})

In [ ]:
legionAuto

warrior1       warrior2
0         Salamander     Salamander
1         Dark Angel     Dark Angel
2        Blood Angel    Blood Angel
3      Imperial Fist  Imperial Fist
4         Space Wolf     Space Wolf
...              ...            ...
49995     Dark Angel     Dark Angel
49996      Iron Hand      Iron Hand
49997    Ultramarine    Ultramarine
49998    Ultramarine    Ultramarine
49999    Ultramarine    Ultramarine

[50000 rows x 2 columns]

In [ ]:
confusion_matrix = pd.crosstab(legionAuto['warrior1'], legionAuto['warrior2'])
print(confusion_matrix)

warrior2       Blood Angel  Dark Angel  Imperial Fist  Iron Hand  Raven Guard  \
warrior1                                                                        
Blood Angel           5583           0              0          0            0   
Dark Angel               0        5385              0          0            0   
Imperial Fist            0           0           5535          0            0   
Iron Hand                0           0              0       5492            0   
Raven Guard              0           0              0          0         5550   
Salamander               0           0              0          0            0   
Space Wolf               0           0              0          0            0   
Ultramarine              0           0              0          0            0   
White Scar               0           0              0          0            0   

warrior2       Salamander  Space Wolf  Ultramarine  White Scar  
warrior1                                   

In [ ]:
cramers_v(confusion_matrix.values)

0.9999999999999999

## 3. "Via di mezzo"

In [ ]:
ani2 = []

for warrior in war:
    if warrior == "White Scar":
        anim = "horse"
    else:
        anim = sample(animals)
    ani2.append(anim)

In [ ]:
print(ani2)

['horse', 'cat', 'dog', 'cat', 'horse', 'horse', 'monke', 'cat', 'dog', 'horse', 'monke', 'monke', 'dog', 'horse', 'dog', 'horse', 'cat', 'dog', 'horse', 'cat', 'dog', 'monke', 'horse', 'cat', 'cat', 'monke', 'horse', 'dog', 'dog', 'horse', 'cat', 'horse', 'horse', 'cat', 'horse', 'dog', 'horse', 'horse', 'dog', 'dog', 'dog', 'cat', 'horse', 'cat', 'cat', 'horse', 'cat', 'horse', 'dog', 'monke', 'horse', 'horse', 'cat', 'dog', 'horse', 'monke', 'cat', 'horse', 'horse', 'dog', 'dog', 'horse', 'monke', 'dog', 'horse', 'monke', 'horse', 'cat', 'monke', 'monke', 'horse', 'horse', 'horse', 'horse', 'cat', 'horse', 'cat', 'horse', 'dog', 'dog', 'horse', 'monke', 'horse', 'horse', 'horse', 'dog', 'dog', 'dog', 'dog', 'horse', 'horse', 'dog', 'horse', 'dog', 'cat', 'cat', 'dog', 'monke', 'cat', 'cat', 'horse', 'dog', 'monke', 'monke', 'monke', 'horse', 'cat', 'horse', 'horse', 'horse', 'dog', 'horse', 'horse', 'horse', 'monke', 'horse', 'monke', 'cat', 'dog', 'horse', 'cat', 'horse', 'horse', 

### Old way (legacy): using the _compute method

AS we can see, if we use it the betas do not change at all.

In [ ]:
result_vdm = my_kernel_one_hot._compute(war, ani2)

In [ ]:
print(result_vdm.value)

0.050304999596928766


In [ ]:
print(result_vdm.alpha)

[0.11111122 0.11111113 0.1111111  0.1111112  0.11111116 0.1111112
 0.1111112  0.11111109 0.11111071]


In [ ]:
print(result_vdm.beta)

[0.2499886  0.2500005  0.24999873 0.25001217]


## Calling directly "_result" [very important experiment, discovered a LOT of things]

If we do not initialize a0 and b0, they will NOT change. BUT, if we initialize them to be all ones, well they will indeed change and at the end their value will highlight the most correlated categories. This is awesome!!

In [ ]:
result_vdm = my_kernel_one_hot._result(war, ani2, kernel_a=True, kernel_b=True, a0=np.ones(9), b0=np.ones(4))

In [ ]:
print(result_vdm.value)

0.04640685317043733


In [ ]:
print(result_vdm.alpha)

[0.11439077 0.11176076 0.11067652 0.11374361 0.11262065 0.11396186
 0.11387618 0.11037154 0.0985981 ]


In [ ]:
print(np.unique(result_vdm.a))

['Blood Angel' 'Dark Angel' 'Imperial Fist' 'Iron Hand' 'Raven Guard'
 'Salamander' 'Space Wolf' 'Ultramarine' 'White Scar']


As we can see, the highest (or lowest) alfa is the one relative to the 'White Scar', that is the warrior that always chooses the 'horse'! (the more "correlated")

In [ ]:
print(result_vdm.beta)

[-0.2374625   0.14634328  0.09377392  0.52242029]


In [ ]:
print(np.unique(result_vdm.b))

['cat' 'dog' 'horse' 'monke']


As we can see, the highest (or lowest) beta is the one relative to the 'horse', that is the steed that's always choosen by the 'White Scar'! (the more "correlated")

### Confusion Matrix extravaganza W

In [ ]:
legionW = pd.DataFrame({'warrior': war, 'steed': ani2})

In [ ]:
legionW

warrior  steed
0         Salamander  horse
1         Dark Angel    cat
2        Blood Angel    dog
3      Imperial Fist    cat
4         Space Wolf  horse
...              ...    ...
49995     Dark Angel  horse
49996      Iron Hand  horse
49997    Ultramarine    dog
49998    Ultramarine    dog
49999    Ultramarine  horse

[50000 rows x 2 columns]

In [ ]:
confusion_matrix = pd.crosstab(legionW['warrior'], legionW['steed'])
print(confusion_matrix)

steed           cat   dog  horse  monke
warrior                                
Blood Angel    1404  1368   1374   1437
Dark Angel     1372  1363   1331   1319
Imperial Fist  1412  1432   1370   1321
Iron Hand      1369  1282   1449   1392
Raven Guard    1397  1373   1405   1375
Salamander     1391  1357   1364   1410
Space Wolf     1410  1371   1400   1428
Ultramarine    1480  1379   1428   1380
White Scar        0     0   5657      0


In [ ]:
cramers_v(confusion_matrix.values)

0.2901832290414661

## White Scar - horse and Raven Guard - cat

In [ ]:
ani3 = []

for warrior in war:
    if warrior == "White Scar":
        anim = "horse"
    elif warrior == "Raven Guard":
        anim="cat"
    else:
        anim = sample(animals)
    ani3.append(anim)

In [ ]:
result_vdmwr = my_kernel_one_hot._result(war, ani3, kernel_a=True, kernel_b=True, a0=np.ones(9), b0=np.ones(4))

In [ ]:
print(result_vdmwr.value)

0.6048854303409855


(0.6216869820138966 with a0 and b0 None)

In [ ]:
print(result_vdmwr.alpha)

[ 0.10288252  0.10439615  0.10390476  0.10643001  0.23881149  0.10557408
  0.1040852   0.10515749 -0.02875831]


In [ ]:
print(np.unique(result_vdmwr.a))

['Blood Angel' 'Dark Angel' 'Imperial Fist' 'Iron Hand' 'Raven Guard'
 'Salamander' 'Space Wolf' 'Ultramarine' 'White Scar']


The 'White Scar' has a big value, as we should expect, and the other "anomalous" value is the 'Raven Guard', that is around 0 (or viceversa). They are indeed the two 'correlated' warriors!!

In [ ]:
print(result_vdmwr.beta)

[ 0.50017336  0.16481489 -0.17000144  0.16501031]


In [ ]:
print(np.unique(result_vdmwr.b))

['cat' 'dog' 'horse' 'monke']


Here 'cat' and 'horse' are the anomalous values. Why cat (or horse) is negative?

In [ ]:
print(war.count('Raven Guard'))
print(war.count('White Scar'))
print(war.count('Iron Hand'))

5550
5657
5492


### Confusion Matrix extravaganza WR

In [ ]:
legionWR = pd.DataFrame({'warrior': war, 'steed': ani3})

In [ ]:
legionWR

warrior  steed
0         Salamander  horse
1         Dark Angel  monke
2        Blood Angel  monke
3      Imperial Fist    dog
4         Space Wolf  horse
...              ...    ...
49995     Dark Angel  horse
49996      Iron Hand    dog
49997    Ultramarine  horse
49998    Ultramarine    dog
49999    Ultramarine  monke

[50000 rows x 2 columns]

In [ ]:
confusion_matrix = pd.crosstab(legionWR['warrior'], legionWR['steed'])
print(confusion_matrix)

steed           cat   dog  horse  monke
warrior                                
Blood Angel    1332  1430   1420   1401
Dark Angel     1346  1324   1370   1345
Imperial Fist  1368  1354   1413   1400
Iron Hand      1405  1317   1346   1424
Raven Guard    5550     0      0      0
Salamander     1405  1343   1381   1393
Space Wolf     1377  1425   1415   1392
Ultramarine    1429  1403   1422   1413
White Scar        0     0   5657      0


In [ ]:
cramers_v(confusion_matrix.values)

0.42748103041187585

In [ ]:
war_i = ["Blood Angel", "White Scar"]

x = [ war_i.count(war)/len(war_i) for war in np.unique(warriors)]

print(x)

[0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5]


In [ ]:
x = np.random.rand(9)
x = x/x.sum()
print(x)
print(x.sum())

[0.1592061  0.1343592  0.05371699 0.01511566 0.23193834 0.13478999
 0.03663098 0.19634293 0.03789983]
1.0
